routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['prefix'=>'administracion', 'middleware'=>'auth'], function(){
	Route::resource('docentes', 'DocentesController');
	Route::get('docentes/destroy/{id}', [
			'uses'=> 'DocentesController@destroy',
			'as'  => 'administracion.docentes.destroy'
	]);

	Route::resource('usuarios', 'UsersController');
	Route::get('usuarios/destroy/{id}', [
			'uses'=> 'UsersController@destroy',
			'as'  => 'administracion.usuarios.destroy'
	]);
   Route::get('usuarios/alta/{id}', [
      'uses'=> 'UsersController@altau',
      'as'  => 'administracion.usuarios.alta'
  ]);
  Route::get('usuarios/bajas/index', [
      'uses'=> 'UsersController@bajasuindex',
      'as'  => 'usuarios.baja.index'
  ]);


//RUTAS PARA ASISTENCIA

  Route::resource('asistencias', 'AsistenciasController');
  Route::get('asistencias/destroy/{id}', [
      'uses'=> 'AsistenciasController@destroy',
      'as'  => 'administracion.asistencias.destroy'
  ]);
   
  Route::get('ingresar-asistencia',[
      'uses'=> 'AsistenciasController@insertarAsistencia',
      'as'  => 'administracion.asistenciasmultiple'
  ]);

/*Route::get('multiple-inserting',[
      'uses'=> 'IndAssingController@multipleInsert',
      'as'  => 'administracion.indicador_assignment.multiple-insert'
  ]); */ 


//RUTA PARA DAR DE ALTA A DOCENTE
  Route::get('docentes/alta/{id}', [
      'uses'=> 'DocentesController@altad',
      'as'  => 'administracion.docentes.alta'
  ]);

  Route::get('assignments/alta/{id}', [
      'uses'=> 'AssignmentsController@alta',
      'as'  => 'administracion.assignments.alta'
  ]);



	Route::resource('asignaturas', 'AsignaturasController');
	Route::get('asignaturas/destroy/{id}', [
			'uses'=> 'AsignaturasController@destroy',
			'as'  => 'administracion.asignaturas.destroy'
	]);
  Route::get('asignaturas/alta/{id}', [
      'uses'=> 'AsignaturasController@altaasig',
      'as'  => 'administracion.asignaturas.alta'
  ]);
  Route::get('asignaturas/bajas/index', [
      'uses'=> 'AsignaturasController@bajasasigindex',
      'as'  => 'asignaturas.baja.index'
  ]);

//Rutas del alumno
  Route::resource('alumnos', 'AlumnosController');
	Route::get('alumnos/destroy/{id}', [
			'uses'=> 'AlumnosController@destroy',
			'as'  => 'administracion.alumnos.destroy'
	]);
  Route::get('alumnos/alta/{id}', [
      'uses'=> 'AlumnosController@alta',
      'as'  => 'administracion.alumnos.alta'
  ]);
  Route::get('alumnos/bajas/index', [
      'uses'=> 'AlumnosController@bajasindex',
      'as'  => 'alumnos.baja.index'
  ]);

  //Rutas de los grados
  Route::resource('grados', 'GradosController');
	Route::get('grados/destroy/{id}', [
			'uses'=> 'GradosController@destroy',
			'as'  => 'administracion.grados.destroy'

	]);

   Route::get('grados/alta/{id}', [
      'uses'=> 'GradosController@altag',
      'as'  => 'administracion.grados.alta'
  ]);
  Route::get('grados/bajas/index', [
      'uses'=> 'GradosController@bajasgindex',
      'as'  => 'grados.baja.index'
  ]);

//PARA AREA INDICADORES MERINO
//*******************************************************************************************
//rutas para areaINDICADORES
  Route::resource('area_indicadores', 'AreaIndicadorController');
  Route::get('area_indicadores/destroy/{id}', [
      'uses'=> 'AreaIndicadorController@destroy',
      'as'  => 'administracion.area_indicadores.destroy'
  ]);


  Route::get('area_indicadores/alta/{id}', [
      'uses'=> 'AreaIndicadorController@altaai',
      'as'  => 'administracion.area_indicadores.alta'
  ]);
  Route::get('area_indicadores/bajas/index', [
      'uses'=> 'AreaIndicador@bajasai',
      'as'  => 'area_indicadores.baja.index'
  ]);


  Route::get('area_indicadores/bajas/index', [
      'uses'=> 'AreaIndicadorController@bajasaiindex',
      'as'  => 'area_indicadores.baja.index'
  ]);


 Route::put('area_indicadores/update/{id}', [
      'uses'=> 'DarBajaController@destroy',
      'as'  => 'administracion.area_indicadores.update1'
  ]);


 //Rutas para indicadores

 Route::resource('indicadores', 'IndicadorController');
  Route::get('indicadores/destroy/{id}', [
      'uses'=> 'IndicadorController@destroy',
      'as'  => 'administracion.indicadores.destroy'
  ]);

   Route::get('indicadores/alta/{id}', [
      'uses'=> 'IndicadorController@altai',
      'as'  => 'administracion.indicadores.alta'
  ]);
  
  Route::get('indicadores/bajas/index', [
      'uses'=> 'IndicadorController@bajasi',
      'as'  => 'indicadores.baja.index'
  ]);


  Route::get('indicadores/bajas/index', [
      'uses'=> 'IndicadorController@bajasiindex',
      'as'  => 'indicadores.baja.index'
  ]);

//******************************************************************************************

  //Ruta para Mostrar Entidades de bajas

Route::get('baja_alumno/index', [
      'uses'=> 'BajasController@bajasalumnos',
      'as'  => 'balumn.index'
  ]);

Route::get('baja_docente/index', [
      'uses'=> 'BajasController@bajasdocentes',
      'as'  => 'badoc.index'
  ]);
//Rutas que muestran el index de las bajas .
  Route::get('baja_asignaciones/index', [
        'uses'=> 'BajasController@bajasassignments',
        'as'  => 'basig.index'
    ]);



  Route::get('altas_asignaciones/index', [
          'uses'=> 'BajasController@altasassignments',
          'as'  => 'alsig.index'
    ]);

  Route::get('baja_registros/index', [
        'uses'=> 'BajasController@bajasrecords',
        'as'  => 'bareg.index'
    ]);Route::get('baja_atribuciones/index', [
          'uses'=> 'BajasController@bajasattributions',
          'as'  => 'batri.index'
      ]);

  Route::get('baja/baja/{id}', [
      'uses'=> 'BajasController@baja',
      'as'  => 'administracion.bajas.baja'
      ]);
    Route::resource('baja', 'BajasController');


Route::resource('bajadoc', 'BDocController');
  Route::get('bajadoc/baja/{id}', [
      'uses'=> 'BDocController@baja',
      'as'  => 'administracion.bajadoc.baja'
  ]);


  Route::resource('asignaciones', 'AssignmentsController');
  Route::get('asignaciones/destroy/{id}', [
      'uses'=> 'AssignmentsController@destroy',
      'as'  => 'administracion.asignaciones.destroy'
  ]);

  Route::resource('registros', 'RecordsController');
  Route::get('registros/destroy/{id}', [
      'uses'=> 'RecordsController@destroy',
      'as'  => 'administracion.registros.destroy'
  ]);

  //*******************************************
  //*******************************************

  //RUTAS DE ATRIBUCIONES ASIGNACION DE GRADOS A ASIGNATURA 

  Route::resource('atribuciones', 'AttributionsController');
  Route::get('atribuciones/destroy/{id}', [
      'uses'=> 'AttributionsController@destroy',
      'as'  => 'administracion.atribuciones.destroy'
  ]);

 Route::get('atribuciones/alta/{id}', [
      'uses'=> 'AttributionsController@altaa',
      'as'  => 'administracion.atribuciones.alta'
  ]);
  
 Route::get('atribuciones/bajas/index', [
      'uses'=> 'AttributionsController@bajasaindex',
      'as'  => 'atribuciones.baja.index'
  ]);



  //*******************************************
  //*******************************************


//OTROS: ASIGNACION DE GRADOS A ALUMNOS

  Route::resource('otros', 'OtrosController');
  Route::get('otros/destroy/{id}', [
      'uses'=> 'OtrosController@destroy',
      'as'  => 'administracion.otros.destroy'
  ]);


 Route::get('otros/alta/{id}', [
      'uses'=> 'OtrosController@altao',
      'as'  => 'administracion.otros.alta'
  ]);
  
 Route::get('otros/bajas/index', [
      'uses'=> 'OtrosController@bajasoindex',
      'as'  => 'otros.baja.index'
  ]);



 //**************************************************
 //**************************************************
  



  Route::resource('indicadors', 'IndicadorController');
  Route::get('indicadors/destroy/{id}', [
      'uses'=> 'IndicadorController@destroy',
      'as'  => 'administracion.indicadors.destroy'
  ]);

  Route::resource('avance_indicadors', 'AvanceIndicadorController');
  Route::get('avance_indicadors/destroy/{id}', [
      'uses'=> 'AvanceIndicadorController@destroy',
      'as'  => 'administracion.avance_indicadors.destroy'
  ]);

 /* Route::resource('lista_baja', 'BareaController');
  Route::get('lista_baja/destroy/{id}', [
      'uses'=> 'BareaController@destroy',
      'as'  => 'administracion.lista_baja.destroy'
  ]);*/
  Route::resource('indicador_baja', 'BIndicadors');
  Route::get('indicador_baja/destroy/{id}', [
      'uses'=> 'BIndicadors@destroy',
      'as'  => 'administracion.indicador_baja.destroy'
  ]);


Route::resource('notas', 'NotasController');
  Route::get('notas/destroy/{id}', [
      'uses'=> 'NotasController@destroy',
      'as'  => 'administracion.notas.destroy'
  ]);
//notas
  Route::get('lenguaje/{idasignatura}');
  Route::get('notas/edit_matematica/{idgrado}/{idasignatura}/{id}', [
              'uses'=> 'NotasController@edit_matematica',
              'as'  => 'administracion/notas/edit_matematica'
  ]);

Route::get('notas/edit_mat/{idgrado}',[
            'uses'=> 'NotasController@edit_mat',
            'as'  => 'administracion.notas.edit_mat'
]);

Route::get('notas/edit_historial/{idgrado}/{idalumno}', [
            'uses'=> 'NotasController@edit_historial',
            'as'  => 'administracion.notas.edit_historial'
]);
Route::get('notas/edit_final/{idgrado}/{idalumno}', [
            'uses'=> 'NotasController@edit_final',
            'as'  => 'administracion.notas.edit_final'
]);
Route::get('notas/edit_finales/{idgrado}/{idalumno}', [
            'uses'=> 'NotasController@edit_finales',

app/Nota.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Nota extends Model
{
    protected $fillable=[ 'idrecord','idtrimestre', 'nota1', 'nota2', 'nota3', 'promedio', 'idasignatura'];

    public function records(){
        return $this->belongsTo('App\Record', 'idrecord');
    }

    public function asignaturas(){
        return $this->belongsTo('App\Asignatura', 'idasignatura');
    }

    public function trimestres(){
        return $this->belongsTo('App\Trimestre', 'idtrimestre');
    }

    public function conductas(){
        return $this->belongsTo('App\Conducta', 'idconducta');
    }

    public function grados(){
        return $this->belongsTo('App\Asignatura', 'idgrado');
    }
}

resources/views/administracion/notas/create.blade.php
@extends('templates.main')

@section('title', 'Registro Docente')

@section('content')
	{!! Form::open(['route'=>'notas.store', 'method'=>'POST']) !!}
  <div class="form-group">
    {!! Form::label('idrecord', 'Alumnos') !!}
    {!! Form::select('idrecord', $alumnos, null, ['class'=>'form-control', 'placeholder'=>'Seleccione un Alumno','required']) !!}
  </div>
	<div class="form-group">
		{!! Form::label('tipo', 'Trimestre') !!}
    {!!  Form::text('tipo', '1')!!}
	</div>
	<div class="form-group">
		{!! Form::label('calificacion', 'Nota') !!}

		{!! Form::text('calificacion', null, ['class'=>'form-control', 'placeholder'=>'Escriba su Nota', 'required']) !!}
	</div>

  <div class="form-group">
    {!! Form::label('idasignatura', 'Listado de Asignaturas') !!}
    {!! Form::select('idasignatura', $asig, null, ['class'=>'form-control', 'placeholder'=>'Seleccione una materia','required']) !!}
  </div>



	<div class="form-group">
		{!! Form::submit('Registrar', ['class'=>'btn btn-primary']) !!}
		<a href="{{ route('docentes.index') }}" class="btn btn-info">Cancelar</a><hr>

	</div>
	{!! Form::close() !!}
@endsection

resources/views/administracion/notas/edit.blade.php
@extends('templates.main')

@section('title', 'Registro de Notas por Materia')

@section('content')

    <h3 align="center">Notas de {{$identificador->nombre}}</h3>
    <h3 align="center">Matemáticas</h3>


    {!! Form::open(['route'=>['notas.update', $identificador], 'method'=>'PUT']) !!}

    <table class="table table-condensed">

        <thead>
          <th>Nombres</th>
          <th>Apellidos</th>
          <th></th>
          <th>Trimestre</th>
          <th>nota 1</th>
          <th>nota 2</th>
          <th>nota 3</th>
          <th></th>

        </thead>

        <tbody>


            @foreach($registros as $registro)
               @if($registro->idgrado == $identificador->id)
							  @if ($registro->activo == 1)
                   <tr>
                     <td>{{ $registro->alumnos->nombres }}</td>
                     <td>{{ $registro->alumnos->apellido_padre }} {{ $registro->alumnos->apellido_madre }}</td>
  {!! Form::close() !!}

{!! Form::open(['route'=>'notas.store', 'method'=>'POST']) !!}
<td>
<div class="form-group">
  {!!  Form::hidden('idrecord', $registro->id)!!}
</div>
</td>
<td style="width:50px;">
  <div class="form-group">
      {!! Form::select('tipo', [''=>'Trim','1Trimestre'=>'1Trimestre', '2Trimestre'=>'2Trimestre', '3Trimestre'=>'3Trimestre'], null, ['class'=>'form-control']) !!}
  </div>
</td>
<td style="width:85px;">
<div class="form-group">
 {!! Form::text('nota1', null, ['class'=>'form-control', 'placeholder'=>'00.00']) !!}
</div>
</td>
<td style="width:85px;">
<div class="form-group">
 {!! Form::text('nota2', null, ['class'=>'form-control', 'placeholder'=>'00.00']) !!}
</div>
</td>
<td style="width:85px;">
<div class="form-group">
 {!! Form::text('nota3', null, ['class'=>'form-control', 'placeholder'=>'00.00']) !!}
</div>
</td>
<td>
<div class="form-group">
 {!! Form::hidden('promedio', '(nota1+nota2+nota3)/3') !!}
</div>
</td>
<td>
<div class="form-group">
  {!!  Form::hidden('idasignatura', '1')!!}
</div>
</td>
                      <td><div class="form-group">
                    		{!! Form::submit('Registrar', ['class'=>'btn btn-primary']) !!}
                    	</div></td>
{!! Form::close() !!}
                  </tr>

								@endif
             @endif
             @endforeach

        </tbody>
	</table>




@endsection

resources/views/administracion/notas/edit_final.blade.php
@extends('templates.main')

@section('title', 'Historial de Notas del Alumno')

@section('content')

    <h3 align="center">{{$identificador->nombre}}</h3>
    <h3 align="center">{{$alumno->nombres}} {{$alumno->apellido_padre}} {{$alumno->apellido_madre}}</h3>
    <h3 align="center">Notas Finales</h3>


    {!! Form::open(['route'=>['notas.update', $identificador], 'method'=>'PUT']) !!}

<!--Registro de Notas Finales -->
</hr>
<div class="container">
  <div style="float:left;width:50%">
<table class="table table-condensed">
    <thead>
      <th>Materias</th>
      <th>Primer Trimestre</th>
      <th>Segundo Trimestre</th>
      <th>Tercer Trimestre</th>
    </thead>
    <tbody>
        @foreach($atribuciones as $atribucion)
           @if($atribucion->idgrado == $identificador->id)
            <tr>
              <td>{{ $atribucion->asignaturas->nombre }}</td>
                   @foreach($notas as $nota)
                       @if($nota->records->idgrado == $identificador->id)
                           @if($nota->records->idalumno == $alumno->id)
                              @if($nota->idasignatura == $atribucion->idasignatura)
                                 @if($nota->idtrimestre == '1')
                                    <td id="td1">{{ $nota->promedio }}</td>
                                 @endif
                                 @if($nota->idtrimestre == '2')
                                    <td id="td2">{{ $nota->promedio }}</td>
                                 @endif
                                 @if($nota->idtrimestre == '3')
                                    <td id="td3">{{ $nota->promedio }}</td>
                                 @endif
                              @endif
                           @endif
                       @endif
                   @endforeach
            </tr>
         @endif
         @endforeach
    </tbody>
</table>
</div>
<div style="float:left;width:20%">
<table class="table table-condensed">
    <thead>

      <th>Nota Final</th>
    </thead>
    <tbody>

            <tr>

                   @foreach($notas as $nota)
                       @if($nota->records->idgrado == $identificador->id)
                           @if($nota->records->idalumno == $alumno->id)
                              @if($nota->idasignatura == '1')
                                    <?php $suma = $suma + $nota->promedio;?>
                              @endif
                           @endif
                       @endif
                   @endforeach
                   <?php $suma=round($suma/3); ?>
                   <td>{{ $suma }}</td>
            </tr>
            <?php $suma=0; ?>

            <tr>

                   @foreach($notas as $nota)
                       @if($nota->records->idgrado == $identificador->id)
                           @if($nota->records->idalumno == $alumno->id)
                              @if($nota->idasignatura == '2')
                                    <?php $suma = $suma + $nota->promedio;?>
                              @endif
                           @endif
                       @endif
                   @endforeach
                   <?php $suma=round($suma/3); ?>
                   <td>{{ $suma }}</td>
            </tr>
            <?php $suma=0; ?>

            <tr>

                   @foreach($notas as $nota)
                       @if($nota->records->idgrado == $identificador->id)
                           @if($nota->records->idalumno == $alumno->id)
                              @if($nota->idasignatura == '3')
                                    <?php $suma = $suma + $nota->promedio;?>
                              @endif
                           @endif
                       @endif
                   @endforeach
                   <?php $suma=round($suma/3); ?>
                   <td>{{ $suma }}</td>
            </tr>
            <?php $suma=0; ?>
            <tr>
              
                   @foreach($notas as $nota)
                       @if($nota->records->idgrado == $identificador->id)
                           @if($nota->records->idalumno == $alumno->id)
                              @if($nota->idasignatura == '4')
                                    <?php $suma = $suma + $nota->promedio;?>
                              @endif
                           @endif
                       @endif
                   @endforeach
                   <?php $suma=round($suma/3); ?>
                   <td>{{ $suma }}</td>
            </tr>
            <?php $suma=0; ?>

    </tbody>
</table>
</div>
</div>
@endsection

resources/views/administracion/notas/edit_finales.blade.php
@extends('templates.main')

@section('title', 'Historial de Notas del Alumno')

@section('content')

    <h3 align="center">{{$identificador->nombre}}</h3>
    <h3 align="center">{{$alumno->nombres}} {{$alumno->apellido_padre}} {{$alumno->apellido_madre}}</h3>
    <h3 align="center">Notas Finales</h3>


    {!! Form::open(['route'=>['notas.update', $identificador], 'method'=>'PUT']) !!}

<!--Registro de Notas Finales -->
</hr>
<div class="container">
  <div style="float:left;width:60%">
<table class="table table-condensed">
    <thead>
      <th>Materias</th>
      <th>Primer Trimestre</th>
      <th>Segundo Trimestre</th>
      <th>Tercer Trimestre</th>
    </thead>
    <tbody>
        @foreach($atribuciones as $atribucion)
           @if($atribucion->idgrado == $identificador->id)
            <tr>
              <td>{{ $atribucion->asignaturas->nombre }}</td>
                   @foreach($notas as $nota)
                       @if($nota->records->idgrado == $identificador->id)
                           @if($nota->records->idalumno == $alumno->id)
                              @if($nota->idasignatura == $atribucion->idasignatura)
                                 @if($nota->idtrimestre == '1')
                                    <td id="td1">{{ $nota->promedio }}</td>
                                 @endif
                                 @if($nota->idtrimestre == '2')
                                    <td id="td2">{{ $nota->promedio }}</td>
                                 @endif
                                 @if($nota->idtrimestre == '3')
                                    <td id="td3">{{ $nota->promedio }}</td>
                                 @endif
                              @endif
                           @endif
                       @endif
                   @endforeach
            </tr>
         @endif
         @endforeach
    </tbody>
</table>
</div>
<div style="float:left;width:10%">
<table class="table table-condensed">
    <thead>

      <th>Nota Final</th>
    </thead>
    <tbody>

            <tr>

                   @foreach($notas as $nota)
                       @if($nota->records->idgrado == $identificador->id)
                           @if($nota->records->idalumno == $alumno->id)
                              @if($nota->idasignatura == '1')
                                    <?php $suma = $suma + $nota->promedio;?>
                              @endif
                           @endif
                       @endif
                   @endforeach
                   <?php $suma=round($suma/3); ?>
                   <td>{{ $suma }}</td>
            </tr>
            <?php $suma=0; ?>

            <tr>

                   @foreach($notas as $nota)
                       @if($nota->records->idgrado == $identificador->id)
                           @if($nota->records->idalumno == $alumno->id)
                              @if($nota->idasignatura == '2')
                                    <?php $suma = $suma + $nota->promedio;?>
                              @endif
                           @endif
                       @endif
                   @endforeach
                   <?php $suma=round($suma/3); ?>
                   <td>{{ $suma }}</td>
            </tr>
            <?php $suma=0; ?>

            <tr>

                   @foreach($notas as $nota)
                       @if($nota->records->idgrado == $identificador->id)
                           @if($nota->records->idalumno == $alumno->id)
                              @if($nota->idasignatura == '3')
                                    <?php $suma = $suma + $nota->promedio;?>
                              @endif
                           @endif
                       @endif
                   @endforeach
                   <?php $suma=round($suma/3); ?>
                   <td>{{ $suma }}</td>
            </tr>
            <?php $suma=0; ?>
            <tr>

                   @foreach($notas as $nota)
                       @if($nota->records->idgrado == $identificador->id)
                           @if($nota->records->idalumno == $alumno->id)
                              @if($nota->idasignatura == '4')
                                    <?php $suma = $suma + $nota->promedio;?>
                              @endif
                           @endif
                       @endif
                   @endforeach
                   <?php $suma=round($suma/3); ?>
                   <td>{{ $suma }}</td>
            </tr>
            <?php $suma=0; ?>
            <tr>

                   @foreach($notas as $nota)
                       @if($nota->records->idgrado == $identificador->id)
                           @if($nota->records->idalumno == $alumno->id)
                              @if($nota->idasignatura == '5')
                                    <?php $suma = $suma + $nota->promedio;?>
                              @endif
                           @endif
                       @endif
                   @endforeach
                   <?php $suma=round($suma/3); ?>
                   <td>{{ $suma }}</td>
            </tr>
            <?php $suma=0; ?>
            <tr>

                   @foreach($notas as $nota)
                       @if($nota->records->idgrado == $identificador->id)
                           @if($nota->records->idalumno == $alumno->id)
                              @if($nota->idasignatura == '6')
                                    <?php $suma = $suma + $nota->promedio;?>
                              @endif
                           @endif
                       @endif
                   @endforeach
                   <?php $suma=round($suma/3); ?>
                   <td>{{ $suma }}</td>
            </tr>
            <?php $suma=0; ?>
            <tr>

                   @foreach($notas as $nota)
                       @if($nota->records->idgrado == $identificador->id)
                           @if($nota->records->idalumno == $alumno->id)
                              @if($nota->idasignatura == '7')
                                    <?php $suma = $suma + $nota->promedio;?>
                              @endif
                           @endif
                       @endif
                   @endforeach
                   <?php $suma=round($suma/3); ?>
                   <td>{{ $suma }}</td>
            </tr>
            <?php $suma=0; ?>

    </tbody>
</table>
</div>
</div>
@endsection

resources/views/administracion/notas/edit_matematica1.blade.php
@extends('templates.main')

@section('title', 'Registro de Notas por Materia')

@section('content')

    <h3 align="center">Notas de {{$identificador->nombre}}</h3>
    <h3 align="center">Tercer Trimestre</h3>
    <h3 align="center">Matemáticas</h3>


    <table class="table table-condensed">

        <thead>
          <th>ID</th>
          <th>ID_Record</th>
          <th>Trimestre</th>
          <th>Nota 1</th>
          <th>Nota 2</th>
          <th>Nota 3</th>
          <th>Promedio</th>
          <th>ID_Asignatura</th>


        </thead>

        <tbody>

            @foreach($notas as $nota)
                   <tr>
                     <td>{{ $nota->id }}</td>
                     <td>{{ $nota->idrecord }}</td>
                     <td>{{ $nota->tipo }}</td>
                     <td>{{ $nota->nota1 }}</td>
                     <td>{{ $nota->nota2 }}</td>
                     <td>{{ $nota->nota3 }}</td>
                     <td>{{ $nota->promedio }}</td>
                     <td>{{ $nota->idasignatura }}</td>

                  </tr>
             @endforeach

        </tbody>
	</table>
@endsection

resources/views/administracion/notas/index.blade.php
@extends('templates.main')

@section('title', 'Grados Asignados')

@section('content')
    <a href="{{ route('alumnos.create') }}" class="btn btn-info">Matricular un nuevo Alumno</a>

    <hr>
    <div class="table-responsive">
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <th>Grados</th>
            <th>Turno</th>
            <th align="center">Asignaciones</th>
            <th align="center">Registro Notas</th>

        </thead>
        <tbody>
          @foreach($registros as $registro)
             @if($registro->iddocente == Auth::user()->iddocente)
             <tr>
                 <td>{{ $registro->grados->nombre }}</td>
                 <td>{{ $registro->grados->turnos->turno }}</td>

                 <td align="center">
                 <a href="{{ route('otros.edit', $registro->grados->id) }}"  class="btn btn-warning">
                   <span class="glyphicon glyphicon-search"  aria-hidden="true"></span>
                 </a>
                 </td>

                 <td align="center">
                 <a href="{{ route('notas.edit_lenguaje', $registro->grados->id, $registro->grados->id) }}"  class="btn btn-primary">
                   <span class="glyphicon glyphicon-list"  aria-hidden="true"></span>
                 </a>
                 </td>

             </tr>
             @endif

             @endforeach

        </tbody>
	</table>
     {{$registros->render()}}
@endsection

resources/views/administracion/notas/menu.blade.php
@extends('templates.main')

@section('title', 'Grados Asignados')

@section('content')
    <a href="{{ route('alumnos.') }}" class="btn btn-info">Matricular un nuevo Alumno</a>
    <hr>
    <a href="{{ route('alumnos.create') }}" class="btn btn-info">Matricular un nuevo Alumno</a>
    <hr>

@endsection